name: stylelint-suitcss
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-suitcss-968.latest.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-suitcss-968.latest.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-stylelint-suitcss-968-latest
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    name: latest
    with:
      package: stylelint-suitcss
      stylelint-version: stylelint@latest
