name: '@wordpress/stylelint-config'
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-wordpress-stylelint-config-54e.latest.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-wordpress-stylelint-config-54e.latest.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref
    }}-wordpress-stylelint-config-54e-latest
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    name: latest
    with:
      package: '@wordpress/stylelint-config'
      stylelint-version: stylelint@latest
